name: CodeQL Analysis

on:
  workflow_dispatch:

jobs:
  codeql-analysis:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout CodeQL Repository
        uses: actions/checkout@v4
        with:
          repository: 'github/codeql'

      - name: Test CodeQL CLI Configuration
        run: |
          ls -al
          
      - name: List CodeQL Queries
        id: list-queries
        run: |
          # List all .ql files in the 'queries' directory
          find CodeQL/queries -type f -name "*.ql" > queries-list.txt

      - name: Run CodeQL Analysis
        id: codeql-analysis
        run: |
          # Create a directory for CodeQL results
          mkdir -p codeql-results

          # Loop through each query file listed in 'queries-list.txt'
          while IFS= read -r query_file; do
            # Extract the query file name without the 'CodeQL/queries/' prefix
            query_name=$(basename "$query_file")

            # Clone the repository
            git clone "$url" target-code

            # Run CodeQL analysis on the cloned repository
            "$extraction_root/codeql/codeql" database create target-code-db --language=javascript --command="npm install && npm run build" --source-root=target-code
            "$extraction_root/codeql/codeql" database analyze target-code-db "$query_file" --format=sarif-latest --output=codeql-results/"$query_name-results.sarif"

            # Clean up the cloned repository
            rm -rf target-code
          done < queries-list.txt

      - name: Upload CodeQL Results
        uses: actions/upload-artifact@v2
        with:
          name: codeql-results
          path: codeql-results
